/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.d156.projetoPOO.view;


import java.util.Date;

/**
 *
 * @author luciano.flopes
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuBarra = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenu();
        mnuCadastroAlu = new javax.swing.JMenuItem();
        mnuAlterarAlu = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenu();
        mnuCadastroProf = new javax.swing.JMenuItem();
        mnuAlterarProf = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        mnuSintetico = new javax.swing.JMenuItem();
        mnuAnalitico = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenu();
        mnuNovaVenda = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuBarra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mnuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clients-icon.png"))); // NOI18N
        mnuCadastro.setText("Cadastro");

        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Office-Client-Male-Light-icon.png"))); // NOI18N
        mnuClientes.setText("Alunos");

        mnuCadastroAlu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-icon.png"))); // NOI18N
        mnuCadastroAlu.setText("Cadastrar");
        mnuCadastroAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroAluActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuCadastroAlu);

        mnuAlterarAlu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-edit-undo-icon.png"))); // NOI18N
        mnuAlterarAlu.setText("Alterar/Excluir");
        mnuAlterarAlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarAluActionPerformed(evt);
            }
        });
        mnuClientes.add(mnuAlterarAlu);

        mnuCadastro.add(mnuClientes);

        mnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/product-icon.png"))); // NOI18N
        mnuProdutos.setText("Professor");

        mnuCadastroProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-icon.png"))); // NOI18N
        mnuCadastroProf.setText("Cadastrar");
        mnuCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroProfActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuCadastroProf);

        mnuAlterarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-edit-undo-icon.png"))); // NOI18N
        mnuAlterarProf.setText("Alterar/Excluir");
        mnuAlterarProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlterarProfActionPerformed(evt);
            }
        });
        mnuProdutos.add(mnuAlterarProf);

        mnuCadastro.add(mnuProdutos);

        mnuBarra.add(mnuCadastro);

        mnuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sheets-icon.png"))); // NOI18N
        mnuRelatorios.setText("Relatórios");

        mnuSintetico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/custom-reports-icon.png"))); // NOI18N
        mnuSintetico.setText("Relatórios Sintético");
        mnuSintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSinteticoActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuSintetico);

        mnuAnalitico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/custom-reports-icon.png"))); // NOI18N
        mnuAnalitico.setText("Relatorio Analítico");
        mnuAnalitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAnaliticoActionPerformed(evt);
            }
        });
        mnuRelatorios.add(mnuAnalitico);

        mnuBarra.add(mnuRelatorios);

        mnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sales-report-icon.png"))); // NOI18N
        mnuVendas.setText("Cadastrar Nota");

        mnuNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shop-cart-add-icon.png"))); // NOI18N
        mnuNovaVenda.setText("Novas Datas");
        mnuNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovaVendaActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuNovaVenda);

        mnuBarra.add(mnuVendas);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAlterarAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarAluActionPerformed
        PesquisaAluno pesquisa = new PesquisaAluno();
        pesquisa.setVisible(true);
    }//GEN-LAST:event_mnuAlterarAluActionPerformed

    private void mnuCadastroAluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroAluActionPerformed
        CadastroAluno cadastro = new CadastroAluno();
        cadastro.setVisible(true);
    }//GEN-LAST:event_mnuCadastroAluActionPerformed

    private void mnuCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroProfActionPerformed
        CadastroProfessor cadastro = new CadastroProfessor();
        cadastro.setVisible(true);
    }//GEN-LAST:event_mnuCadastroProfActionPerformed

    private void mnuNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovaVendaActionPerformed
QuadrodeNotas qnotas  = new QuadrodeNotas();
qnotas.setVisible(true);

    }//GEN-LAST:event_mnuNovaVendaActionPerformed

    private void mnuAlterarProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlterarProfActionPerformed
        PesquisaProfessor pesquisa = new PesquisaProfessor();
        pesquisa.setVisible(true);
    }//GEN-LAST:event_mnuAlterarProfActionPerformed

    private void mnuSinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSinteticoActionPerformed
    }//GEN-LAST:event_mnuSinteticoActionPerformed

    private void mnuAnaliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAnaliticoActionPerformed
    }//GEN-LAST:event_mnuAnaliticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuAlterarAlu;
    private javax.swing.JMenuItem mnuAlterarProf;
    private javax.swing.JMenuItem mnuAnalitico;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroAlu;
    private javax.swing.JMenuItem mnuCadastroProf;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenuItem mnuNovaVenda;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenuItem mnuSintetico;
    private javax.swing.JMenu mnuVendas;
    // End of variables declaration//GEN-END:variables
}
